name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      
      - name: Clone vinagent
        run: git clone https://github.com/datascienceworld-kan/vinagent.git
      
      - name: Install from source
        run: pip install ./vinagent --verbose
      - name: Verify vinagent installation
        run: python -c "import vinagent; print(vinagent.__file__)" || { echo "Failed to import vinagent"; exit 1; }
      - name: Install dependencies
        run: pip install mkdocs-material mkdocstrings[python] ruff
      - name: Test FlowStateGraph import
        run: python -c "from vinagent.graph.operator import FlowStateGraph; print(FlowStateGraph)" || { echo "Failed to import FlowStateGraph"; exit 1; }
      - name: Add vinagent to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$PWD/vinagent" >> $GITHUB_ENV
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
